<template>
	<div class="Category">
		<h1>品类</h1>
    <div class="wrapper">
      <ul class="content">
        <li>'种类'1</li>
        <li>'种类'2</li>
        <li>'种类'3</li>
        <li>'种类'4</li>
        <li>'种类'5</li>
        <li>'种类'6</li>
        <li>'种类'7</li>
        <li>'种类'8</li>
        <li>'种类'9</li>
        <li>'种类'10</li>
        <li>'种类'11</li>
        <li>'种类'12</li>
        <li>'种类'13</li>
        <li>'种类'14</li>
        <li>'种类'15</li>
        <li>'种类'16</li>
        <li>'种类'17</li>
        <li>'种类'18</li>
        <li>'种类'19</li>
        <li>'种类'20</li>
        <li>'种类'21</li>
        <li>'种类'22</li>
        <li>'种类'23</li>
        <li>'种类'24</li>
        <li>'种类'25</li>
        <li>'种类'26</li>
        <li>'种类'27</li>
        <li>'种类'28</li>
        <li>'种类'29</li>
        <li>'种类'30</li>
        <li>'种类'31</li>
        <li>'种类'32</li>
        <li>'种类'33</li>
        <li>'种类'34</li>
        <li>'种类'35</li>
        <li>'种类'36</li>
        <li>'种类'37</li>
        <li>'种类'38</li>
        <li>'种类'39</li>
        <li>'种类'40</li>
        <li>'种类'41</li>
        <li>'种类'42</li>
        <li>'种类'43</li>
        <li>'种类'44</li>
        <li>'种类'45</li>
        <li>'种类'46</li>
        <li>'种类'47</li>
        <li>'种类'48</li>
        <li>'种类'49</li>
        <li>'种类'50</li>
        <li>'种类'51</li>
        <li>'种类'52</li>
        <li>'种类'53</li>
        <li>'种类'54</li>
        <li>'种类'55</li>
        <li>'种类'56</li>
        <li>'种类'57</li>
        <li>'种类'58</li>
        <li>'种类'59</li>
        <li>'种类'60</li>
        <li>'种类'61</li>
        <li>'种类'62</li>
        <li>'种类'63</li>
        <li>'种类'64</li>
        <li>'种类'65</li>
        <li>'种类'66</li>
        <li>'种类'67</li>
        <li>'种类'68</li>
        <li>'种类'69</li>
        <li>'种类'70</li>
        <li>'种类'71</li>
        <li>'种类'72</li>
        <li>'种类'73</li>
        <li>'种类'74</li>
        <li>'种类'75</li>
        <li>'种类'76</li>
        <li>'种类'77</li>
        <li>'种类'78</li>
        <li>'种类'79</li>
        <li>'种类'80</li>
        <li>'种类'81</li>
        <li>'种类'82</li>
        <li>'种类'83</li>
        <li>'种类'84</li>
        <li>'种类'85</li>
        <li>'种类'86</li>
        <li>'种类'87</li>
        <li>'种类'88</li>
        <li>'种类'89</li>
        <li>'种类'90</li>
        <li>'种类'91</li>
        <li>'种类'92</li>
        <li>'种类'93</li>
        <li>'种类'94</li>
        <li>'种类'95</li>
        <li>'种类'96</li>
        <li>'种类'97</li>
        <li>'种类'98</li>
        <li>'种类'99</li>
        <li>'种类'100</li>
        <li>'种类'101</li>
        <li>'种类'102</li>
        <li>'种类'103</li>
        <li>'种类'104</li>
        <li>'种类'105</li>
        <li>'种类'106</li>
        <li>'种类'107</li>
        <li>'种类'108</li>
        <li>'种类'109</li>
        <li>'种类'110</li>
        <li>'种类'111</li>
        <li>'种类'112</li>
        <li>'种类'113</li>
        <li>'种类'114</li>
        <li>'种类'115</li>
        <li>'种类'116</li>
        <li>'种类'117</li>
        <li>'种类'118</li>
        <li>'种类'119</li>
        <li>'种类'120</li>
        <li>'种类'121</li>
        <li>'种类'122</li>
        <li>'种类'123</li>
        <li>'种类'124</li>
        <li>'种类'125</li>
        <li>'种类'126</li>
        <li>'种类'127</li>
        <li>'种类'128</li>
        <li>'种类'129</li>
        <li>'种类'130</li>
        <li>'种类'131</li>
        <li>'种类'132</li>
        <li>'种类'133</li>
        <li>'种类'134</li>
        <li>'种类'135</li>
        <li>'种类'136</li>
        <li>'种类'137</li>
        <li>'种类'138</li>
        <li>'种类'139</li>
        <li>'种类'140</li>
        <li>'种类'141</li>
        <li>'种类'142</li>
        <li>'种类'143</li>
        <li>'种类'144</li>
        <li>'种类'145</li>
        <li>'种类'146</li>
        <li>'种类'147</li>
        <li>'种类'148</li>
        <li>'种类'149</li>
        <li>'种类'150</li>
        <li>'种类'151</li>
        <li>'种类'152</li>
        <li>'种类'153</li>
        <li>'种类'154</li>
        <li>'种类'155</li>
        <li>'种类'156</li>
        <li>'种类'157</li>
        <li>'种类'158</li>
        <li>'种类'159</li>
        <li>'种类'160</li>
        <li>'种类'161</li>
        <li>'种类'162</li>
        <li>'种类'163</li>
        <li>'种类'164</li>
        <li>'种类'165</li>
        <li>'种类'166</li>
        <li>'种类'167</li>
        <li>'种类'168</li>
        <li>'种类'169</li>
        <li>'种类'170</li>
        <li>'种类'171</li>
        <li>'种类'172</li>
        <li>'种类'173</li>
        <li>'种类'174</li>
        <li>'种类'175</li>
        <li>'种类'176</li>
        <li>'种类'177</li>
        <li>'种类'178</li>
        <li>'种类'179</li>
        <li>'种类'180</li>
        <li>'种类'181</li>
        <li>'种类'182</li>
        <li>'种类'183</li>
        <li>'种类'184</li>
        <li>'种类'185</li>
        <li>'种类'186</li>
        <li>'种类'187</li>
        <li>'种类'188</li>
        <li>'种类'189</li>
        <li>'种类'190</li>
        <li>'种类'191</li>
        <li>'种类'192</li>
        <li>'种类'193</li>
        <li>'种类'194</li>
        <li>'种类'195</li>
        <li>'种类'196</li>
        <li>'种类'197</li>
        <li>'种类'198</li>
        <li>'种类'199</li>
        <li>'种类'200</li>
      </ul>
    </div>
	</div>
</template>

<script>
  import BScroll from '@better-scroll/core'
  export default {
    name: 'Category',
    data() {
      return {
        scroll: null
      }
    },
    mounted() {
      this.scroll = new BScroll(document.querySelector('.wrapper'))
      
    }
  }
</script>

<style scoped>
  .wrapper {
    height: 300px;
    overflow: hidden;
  }
</style>
